---
- name: Imprimir facts del sistema
  hosts: localhost
  connection: local
  gather_facts: true
  tasks:
    - name: Imprimir facts existentes
      debug:
        msg: "{{ item }}: {{ ansible_facts[item] }}"
      loop:
        - hostname
        - ansible_os_family
        - ansible_distribution
        - ansible_version.full
      when: ansible_facts[item] is defined
